---
apiVersion: batch/v1
kind: Job
metadata: 
  name: hellojob
spec:
  template: 
    metadata: 
      name: jgitobpod
    spec:
      restartPolicy: OnFailure
      containers: 
        - image: alpine
          command:
            - sleep
            - 10s    